package anwKonto;

import anwKonto.Konto;
import java.io.*;
/*
 * KontoVerwaltung.java
 *
 * Created on 24. November 2008, 09:52
 */



/**
 *
 * @author  mosimann
 */
public class KontoVerwaltung extends javax.swing.JFrame {

    /** Creates new form KontoVerwaltung */
    public KontoVerwaltung() {
        initComponents();
        konto = new Konto();
        jButton4.setEnabled(false);
        txtVorname.setName("vorname");
        jRadioEinzahlen.setName("einzahlen");
        jButton3.setName("speichern");
        jButton1.setName("neu");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKontonummer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVorname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBetrag = new javax.swing.JTextField();
        jRadioEinzahlen = new javax.swing.JRadioButton();
        jRadioAbheben = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton5.setText("Öffnen");
        jButton5.setName("oeffnen"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5Oeffnen(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kontoverwaltung");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtKontonummer.setName("kontonummer"); // NOI18N

        jLabel2.setText("Kontonummer:");

        jLabel3.setText("Name:");

        txtName.setName("nachname"); // NOI18N

        jLabel4.setText("Vorname:");

        jLabel5.setText("Saldo:");

        txtSaldo.setEditable(false);
        txtSaldo.setName("saldo"); // NOI18N
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        jLabel6.setText("Betrag (CHF):");

        txtBetrag.setName("betrag"); // NOI18N
        txtBetrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetragActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEinzahlen);
        jRadioEinzahlen.setSelected(true);
        jRadioEinzahlen.setText("einzahlen");
        jRadioEinzahlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEinzahlenActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAbheben);
        jRadioAbheben.setText("abheben");

        jButton1.setText("Neu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Neu(evt);
            }
        });

        jButton2.setText("Öffnen");
        jButton2.setName("oeffnen"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oeffnen(evt);
            }
        });

        jButton3.setText("Speichern");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speichern(evt);
            }
        });

        jButton4.setText("Geld transferieren");
        jButton4.setName("geldtransfer"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeldTransfer(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVorname)
                            .addComponent(txtName)
                            .addComponent(txtKontonummer, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtSaldo)
                            .addComponent(jRadioAbheben)
                            .addComponent(jRadioEinzahlen)
                            .addComponent(txtBetrag))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKontonummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(6, 6, 6)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBetrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioEinzahlen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioAbheben))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRadioEinzahlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEinzahlenActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioEinzahlenActionPerformed

private void Speichern(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speichern
// Speichern    
    try {
        konto.setKnr(Integer.parseInt(txtKontonummer.getText()));
        konto.setName(txtName.getText());
        konto.setVorname(txtVorname.getText());
        if (!konto.getName().equals("")) {
            konto.Speichern();
            jButton3.setEnabled(false);
            jButton4.setEnabled(true);
        }
    }
    catch (NumberFormatException e) {txtKontonummer.setText("Fehler!");}
    catch (IOException e) {txtKontonummer.setText("Fehler!");}
}//GEN-LAST:event_Speichern

private void Neu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Neu
// Neu   
    txtKontonummer.setText("");
    txtName.setText("");
    txtVorname.setText("");
    txtSaldo.setText("");
    txtBetrag.setText("");
    jRadioEinzahlen.setSelected(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(false);
    konto = new Konto();
}//GEN-LAST:event_Neu

private void Oeffnen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oeffnen
// Öffnen    
    try {
        konto = new Konto(Integer.parseInt(txtKontonummer.getText()));
        txtName.setText(konto.getName());
        txtVorname.setText(konto.getVorname());
        txtSaldo.setText(Double.toString(konto.getSaldo()));
        jButton3.setEnabled(false);
        jButton4.setEnabled(true);
    }
    catch(Exception e) {txtKontonummer.setText("Fehler!");}
}//GEN-LAST:event_Oeffnen

private void GeldTransfer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeldTransfer
// Geld transferieren
    try {
        if (jRadioEinzahlen.isSelected()) {
            konto.Einzahlen(Double.parseDouble(txtBetrag.getText()));
        } else {
            konto.Abheben(Double.parseDouble(txtBetrag.getText()));
        }
        txtSaldo.setText(Double.toString(konto.getSaldo()));
    }
    catch (Exception e) {}
}//GEN-LAST:event_GeldTransfer

    private void jButton5Oeffnen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5Oeffnen
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5Oeffnen

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtBetragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetragActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetragActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoVerwaltung().setVisible(true);
            }
        });
    }
    
    // mosimann
    private Konto konto;
    // End mosimann

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioAbheben;
    private javax.swing.JRadioButton jRadioEinzahlen;
    private javax.swing.JTextField txtBetrag;
    private javax.swing.JTextField txtKontonummer;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtVorname;
    // End of variables declaration//GEN-END:variables

}
